project 'ChatPlatformApp.xcodeproj'
workspace '../ChatPlatform.xcworkspace'
source 'https://github.com/CocoaPods/Specs.git'
inhibit_all_warnings!

platform :ios, "10.0"

### GENERAL

def default_pods
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'SwiftLint'
    pod 'Sourcery'
end

target :ChatPlatformApp do
    default_pods
    use_frameworks!
end